const KEY="grafitex_contracts_v1";
const defaultConditions="Adelanto 50%\nCancelación del saldo contra entrega o confirmación de envío\nSe empieza el diseño una vez confirmado el depósito\nFecha de entrega: 07 días hábiles después de aprobado el diseño.";
const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat("es-PE",{style:"currency",currency:"PEN"}).format(Number(n||0));
const today=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
let current=null,items=[];
const getAll=()=>{try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return[]}},setAll=v=>localStorage.setItem(KEY,JSON.stringify(v));
function fresh(){current=null;items=[{quantity:"",unit:"Millares",description:"",unitPrice:""}];$("contractNumber").value=String(Date.now()).slice(-7);$("contractDate").value=today();["contactName","company","taxId","phone","deposit"].forEach(id=>$(id).value="");$("showConditions").checked=false;$("conditions").value=defaultConditions;$("conditionsWrap").classList.add("hidden");$("saveBtn").textContent="Guardar contrato";$("notice").innerHTML="";renderItems();calc();window.scrollTo(0,0)}
function renderItems(){$("items").innerHTML=items.map((it,i)=>`<article class="item"><div class="itemHead"><b>Producto ${i+1}</b>${items.length>1?`<button data-remove="${i}">Quitar</button>`:""}</div><label>Descripción<textarea data-i="${i}" data-f="description" rows="2" placeholder="Ej.: Cajas en Foldcote C14, full color">${it.description||""}</textarea></label><div class="itemGrid"><label>Cantidad<input data-i="${i}" data-f="quantity" inputmode="decimal" value="${it.quantity}"></label><label>Unidad<select data-i="${i}" data-f="unit">${["Unidad","Unidades","Millar","Millares","Ciento","Servicio"].map(x=>`<option ${x===it.unit?"selected":""}>${x}</option>`).join("")}</select></label><label>Precio unitario<input data-i="${i}" data-f="unitPrice" inputmode="decimal" value="${it.unitPrice}"></label><div class="subtotal"><small>Subtotal</small><b>${money(Number(it.quantity)*Number(it.unitPrice))}</b></div></div></article>`).join("");}
function calc(){const total=items.reduce((s,x)=>s+Number(x.quantity||0)*Number(x.unitPrice||0),0),bal=total-Number($("deposit").value||0);$("total").textContent=money(total);$("balance").textContent=money(bal);$("numberBadge").textContent=$("contractNumber").value;return{total,balance:bal}}
function data(){const c=calc();return{id:current?.id||Date.now(),contractNumber:$("contractNumber").value.trim(),contractDate:$("contractDate").value,contactName:$("contactName").value.trim(),company:$("company").value.trim(),taxId:$("taxId").value.trim(),phone:$("phone").value.trim(),items:items.filter(x=>x.description.trim()),deposit:Number($("deposit").value||0),showConditions:$("showConditions").checked,conditions:$("conditions").value.trim(),total:c.total,balance:c.balance,updatedAt:new Date().toISOString()}}
function save(){const c=data();if(!c.contractNumber||!c.contractDate||(!c.contactName&&!c.company)){notice("Complete el número, la fecha y el cliente o empresa.",true);return}let all=getAll(),ix=all.findIndex(x=>x.id===c.id);if(ix>=0)all[ix]=c;else all.unshift(c);setAll(all);current=c;$("saveBtn").textContent="Actualizar contrato";notice("Contrato guardado correctamente.");renderHistory()}
function notice(t,error=false){$("notice").innerHTML=`<div class="notice ${error?"error":""}">${t}</div>`}
function openContract(c){current=c;["contractNumber","contractDate","contactName","company","taxId","phone","deposit","conditions"].forEach(id=>$(id).value=c[id]??"");$("showConditions").checked=!!c.showConditions;$("conditionsWrap").classList.toggle("hidden",!c.showConditions);items=c.items?.length?structuredClone(c.items):[{quantity:"",unit:"Millares",description:"",unitPrice:""}];$("saveBtn").textContent="Actualizar contrato";renderItems();calc();switchTab("form");window.scrollTo(0,0)}
function renderHistory(){const q=$("search").value.toLowerCase(),all=getAll();$("count").textContent=all.length;const list=all.filter(c=>[c.contractNumber,c.contactName,c.company,c.taxId,c.phone].join(" ").toLowerCase().includes(q));$("history").innerHTML=list.length?list.map(c=>`<button class="historyCard" data-open="${c.id}"><div><small>N.° ${c.contractNumber}</small><b>${c.company||c.contactName||"Cliente sin nombre"}</b><span>${c.taxId?`RUC/DNI ${c.taxId} · `:""}${new Date(c.contractDate+"T12:00:00").toLocaleDateString("es-PE")}</span></div><div><b>${money(c.total)}</b><span>Ver ›</span></div></button>`).join(""):`<div class="empty"><b>No se encontraron contratos</b><p>Pruebe con otro nombre, RUC o número.</p></div>`}
function switchTab(t){document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.tab===t));$("formView").classList.toggle("hidden",t!=="form");$("historyView").classList.toggle("hidden",t!=="history");if(t==="history")renderHistory()}
function printPdf(){const c=data();if(!c.contactName&&!c.company)return notice("Primero escriba el nombre del cliente o empresa.",true);const rows=c.items.map(x=>`<tr><td>${x.quantity}</td><td>${x.unit}</td><td>${x.description}</td><td>${money(x.unitPrice)}</td><td>${money(Number(x.quantity)*Number(x.unitPrice))}</td></tr>`).join("")+Array.from({length:Math.max(0,10-c.items.length)},()=>`<tr class="blank"><td></td><td></td><td></td><td></td><td></td></tr>`).join("");$("printContract").innerHTML=`<div class="printTop"><h1>CONTRATO</h1><b>${c.contractNumber}</b></div><div class="business"><img src="logo-grafitec.svg?v=2"><div><b>GRAFITEC WORLD PERÚ</b><span>DE: Martha Elena Diaz Espinoza</span><span>RUC: 10164559012</span><span>Atención al cliente y showroom: Av. José Pardo 223, piso 9 - a 1 cuadra de la pileta de Miraflores - Lima</span><span>Atención al cliente y showroom: Av. Leonardo Ortiz 158, int. 1A - frente aduanas, ex SUNAT - Chiclayo</span><span>Cel.: 920102240</span></div></div><div class="client"><p><b>Sres.:</b><span>${c.contactName}</span></p><p><b>Fecha:</b><span>${new Date(c.contractDate+"T12:00:00").toLocaleDateString("es-PE")}</span></p><p><b>Empresa:</b><span>${c.company}</span></p><p><b>RUC:</b><span>${c.taxId}</span></p><p><b>Cel.:</b><span>${c.phone}</span></p></div><table><thead><tr><th>CANT.</th><th>UNIDAD</th><th>DESCRIPCIÓN</th><th>P. UNIT.</th><th>TOTAL</th></tr></thead><tbody>${rows}</tbody></table><div class="totals"><p><b>TOTAL</b><span>${money(c.total)}</span></p><p><b>A CUENTA</b><span>${money(c.deposit)}</span></p><p><b>SALDO</b><span>${money(c.balance)}</span></p></div>${c.showConditions&&c.conditions?`<div class="printConditions"><b>Condiciones:</b>${c.conditions.split("\n").filter(Boolean).map(x=>`<p>• ${x}</p>`).join("")}</div>`:""}<div class="bank"><b>Cta. Ahorros BCP Soles: 305 09604979 0 85</b><b>CCI: 00230510960497908517</b><b>Martha Elena Diaz Espinoza</b></div>`;const originalTitle=document.title,clientFile=(c.contactName||c.company||"cliente").trim().replace(/[\\/:*?"<>|]/g,"").replace(/\s+/g,"_");document.title=`contrato_${clientFile}`;const restoreTitle=()=>{document.title=originalTitle;window.removeEventListener("afterprint",restoreTitle)};window.addEventListener("afterprint",restoreTitle);window.print();setTimeout(restoreTitle,1500)}
$("newBtn").onclick=fresh;$("addItem").onclick=()=>{items.push({quantity:"",unit:"Millares",description:"",unitPrice:""});renderItems()};$("saveBtn").onclick=save;$("pdfBtn").onclick=printPdf;$("deposit").oninput=calc;$("contractNumber").oninput=calc;$("showConditions").onchange=e=>$("conditionsWrap").classList.toggle("hidden",!e.target.checked);$("search").oninput=renderHistory;document.querySelector("nav").onclick=e=>e.target.closest("button[data-tab]")&&switchTab(e.target.closest("button").dataset.tab);$("items").oninput=e=>{const t=e.target;if(t.dataset.i!==undefined){items[Number(t.dataset.i)][t.dataset.f]=t.value;calc();if(t.dataset.f==="quantity"||t.dataset.f==="unitPrice"){const subtotal=t.closest(".item").querySelector(".subtotal b");subtotal.textContent=money(Number(items[Number(t.dataset.i)].quantity||0)*Number(items[Number(t.dataset.i)].unitPrice||0))}}};$("items").onchange=e=>{const t=e.target;if(t.dataset.i!==undefined){items[Number(t.dataset.i)][t.dataset.f]=t.value;calc()}};$("items").onclick=e=>{const b=e.target.closest("[data-remove]");if(b){items.splice(Number(b.dataset.remove),1);renderItems();calc()}};$("history").onclick=e=>{const b=e.target.closest("[data-open]");if(b)openContract(getAll().find(c=>c.id===Number(b.dataset.open)))};
$("exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify(getAll(),null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`respaldo-contratos-grafitex-${today()}.json`;a.click();URL.revokeObjectURL(a.href)};$("importFile").onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());if(!Array.isArray(d))throw 0;setAll(d);renderHistory();notice("Respaldo importado correctamente.")}catch{notice("El archivo de respaldo no es válido.",true)}};fresh();renderHistory();
